language: ruby
rvm:
- 2.4

before_install:
  - gem update --system
  - gem install bundler

script:
  - "npm install"
  - "npm run build"

before_deploy:
  - chmod +x ./deploy.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true

env:
  - JEKYLL_ENV=production

os:
  - osx
