language: ruby
rvm:
- 2.3

script:
  - "bundle exec jekyll build --config _config.yml"

before_deploy:
  - chmod +x ./deploy.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true

env:
  - JEKYLL_ENV=production