language: ruby
rvm:
- 2.1
script: "bundle exec jekyll build"

all_branches: true

env:
  global:
  - GH_REPO="marabesi/marabesi.com"

before_deploy:
  - chmod u+x ./deploy.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true