language: ruby
rvm:
- 2.1

script:
  - "npm install -g bower"
  - "bower install"
  - "bundle exec jekyll build"

before_deploy:
  - chmod +x ./deploy.sh

deploy:
  provider: script
  script: "./deploy.sh"
