language: ruby
rvm:
- 2.6

before_install:
  - gem update --system
  - gem install bundler

script:
  - "npm install --dev"
  - "npm run build"

before_deploy:
  - chmod +x ./deploy.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true

env:
  global:
    - JEKYLL_ENV=production
    - NODE_ENV=production

os:
  - osx
