# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marabesi
email: matheus.marabesi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The knowledge must be shared
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marabesi.com" # the base hostname & protocol for your site
twitter_username: MatheusMarabesi
github_username:  marabesi

# Custom settings
collections:
  newbies:
    output: true

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
